### ISSUE TITLE
Наименование

### ISSUE THREAD

**Issue by algolGuru** [Vorun5/TL-Practice#2]
https://github.com/Vorun5/TL-Practice/blob/5359327e027796311f9ee0644b3a5e0a76e44a1c/DataBase/Shop(sql)/Shop/Program.cs#L40
Именования в одном стиле. Idproperty или propertyId, решай уж сам

**Comment by Vorun5** [comment]
Исправил. Привёл всё к виду propertyId.

**Comment by Vorun5** [comment]
Исправил. Привёл всё к виду propertyId.
